name: Build

permissions:
  contents: write

on:
  push:
    branches: [ master ]
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup yq
        uses: vegardit/gha-setup-yq@v1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get release version
        id: app_version
        env:
          TZ: 'Asia/Tokyo'
        run: | # shell
          CURRENT_VERSION=$(yq '.version' pubspec.yaml)
          HEAD=$(date +'%Y.%-m.')
          if [[ "$CURRENT_VERSION" == "$HEAD"* ]]; then
            PATCH=$(echo "$CURRENT_VERSION" | awk -F. '{print $NF}' | awk '{print $1 + 1}')
          else
            PATCH=0
          fi
          echo "release=$HEAD$PATCH" >> $GITHUB_OUTPUT

      - name: Rewrite pubspec.yaml
        run: | # shell
          sed -i 's/version:.*/version: ${{ steps.app_version.outputs.release }}/' pubspec.yaml
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pubspec.yaml
          git commit -m "release: ${{ steps.app_version.outputs.release }}"
          git push

      - name: Get dependencies
        run: flutter pub get

      - name: Build
        run: |
          echo '${{ secrets.KEYSTORE_BASE64 }}' | base64 -d > android/release.keystore
          export STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
          export KEY_ALIAS='${{ secrets.KEY_ALIAS }}'
          export KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}'
          flutter build apk --release

      - name: Prepare deploy
        run: |
          mkdir dist
          cp ./build/app/outputs/flutter-apk/app-release.apk ./

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.app_version.outputs.release }}
          tag_name: v${{ steps.app_version.outputs.release }}
          files: app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
