name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get commit count
        id: commit_count
        run: echo "number=$(git rev-list HEAD --count)" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build
        run: flutter build apk --release --build-number=${{ steps.commit_count.outputs.number }}

      - name: Get flutter version
        id: flutter_version
        uses: its404/get-flutter-version@v1.0.0

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: ${{ steps.flutter_version.outputs.version_number }}+${{ steps.commit_count.outputs.number }}
          files: build/app/outputs/flutter-apk/app-release.apk