name: Build

on:
  push:
    branches: [ master ]
    paths:
      - 'lib/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit count
        id: commit_count
        run: echo "number=$(git rev-list HEAD --count)" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build
        run: |
          echo '${{ secrets.KEYSTORE_BASE64 }}' | base64 -d > android/release.keystore
          export STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
          export KEY_ALIAS='${{ secrets.KEY_ALIAS }}'
          export KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}'
          flutter build apk --release --build-number=${{ steps.commit_count.outputs.number }}

      - name: Get flutter version
        id: flutter_version
        run: |
          VERSION=$(cat pubspec.yaml | grep 'version:' | awk '{print $2}' | awk -F '+' '{print $1}')
          echo "version_number=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare deploy
        run: |
          mkdir dist
          cp build/app/outputs/flutter-apk/app-release.apk dist/
          echo '{"version": "${{ steps.flutter_version.outputs.version_number }}", "build": "${{ steps.commit_count.outputs.number }}", "datetime": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'", "commit": "'$(git rev-parse --short HEAD)'", "size": '$(stat -c%s dist/app-release.apk)'}' > dist/version.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'