name: Build

permissions:
  contents: write

on:
  push:
    branches: [ master ]
    paths:
      - 'lib/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit count
        id: commit_count
        run: echo "number=$(git rev-list HEAD --count)" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build
        run: |
          echo '${{ secrets.KEYSTORE_BASE64 }}' | base64 -d > android/release.keystore
          export STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
          export KEY_ALIAS='${{ secrets.KEY_ALIAS }}'
          export KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}'
          export GOOGLE_MAPS_API_KEY='${{ secrets.GOOGLE_MAPS_API_KEY }}'
          flutter build apk --release --build-number=${{ steps.commit_count.outputs.number }}

      - name: Get flutter version
        id: flutter_version
        run: |
          VERSION=$(cat pubspec.yaml | grep 'version:' | awk '{print $2}' | awk -F '+' '{print $1}')
          echo "version_number=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare deploy
        run: |
          mkdir dist
          cp ./build/app/outputs/flutter-apk/app-release.apk ./

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.flutter_version.outputs.version_number }}+${{ steps.commit_count.outputs.number }}
          tag_name: v${{ steps.flutter_version.outputs.version_number }}+${{ steps.commit_count.outputs.number }}
          files: app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
